version: "3.3"
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    env_file:
      - ./.env
    command:
      - ./run.sh
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db